import type { Metadata } from "next";
import "./globals.css";
import { NavigationHeader } from "./_components/navigationHeader";

export const metadata: Metadata = {
  title: "アキバ総研アーカイブ",
  //description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`antialiased min-h-screen flex flex-col`}
      >
        <NavigationHeader></NavigationHeader>
        {children}
        <div>
          全てのデータは<a href="https://akiba-souken.com/" target="_blank" className="original-href">アキバ総研</a>より。
          Github:<a href="https://github.com/fushihara/akiba-souken-archive" target="_blank" className="original-href">archive</a> , <a href="https://github.com/fushihara/akiba-souken-crawler" target="_blank" className="original-href">crawler</a>
        </div>
      </body>
    </html>
  );
}
